media: static/img
content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    view: 
      fields: [title, date]
    fields:
      - { name: title, label: Title, type: string}
      - { name: date, label: Date, type: date}
      - { name: cover, label: Image, type: object}
      - { name: body, label: Body, type: rich-text}
      
  